train:
  dist_url: "tcp://localhost:12754"
  multiprocessing_distributed: true
  world_size: 1
  rank: 0

  batch_size: 32
  epochs: 50
  seed: 3407
  model: clipiqa  

dataset:
  dataset: [livec]
  resize_size: [224, 224]

save_path: "./EXP/SingleDataset/clipiqa"
